# Netlify config for deploying the Vite React client in wave-client

[build]
  base = "wave-client"
  publish = "dist"
  command = "npm install && npm run build"

# SPA fallback so client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Proxy API to an external server (e.g., Render) if you prefer relative /api calls
# Uncomment and set your server URL if you don't use VITE_API_BASE
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-wave-server.onrender.com/:splat"
#   status = 200
#   force = true
