services:
  - type: web
    name: wave-server
    env: node
    plan: free
    rootDir: wave-server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: static_site
    name: wave-client
    rootDir: wave-client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_API_BASE
        fromService:
          type: web
          name: wave-server
          property: url
